version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./demo-tracker-frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    # volumes:
    #   - ./demo-tracker-frontend:/app_frontend
    depends_on:
      - backend

  backend:
    container_name: backend
    restart: always
    build:
      context: ./demo-tracker-backend
    # command: ["npm", "run", "start:migrate:prod"]
    command: ["sh", "-c", "npm run build && npm run start:migrate:prod"]

    ports:
      - "3001:3000"
    volumes:
      - ./demo-tracker-backend:/app_backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://root:passbackendtrackerword@db:3306/demo_tracker_mysql?connect_timeout=300"

  mysql:
    container_name: db
    restart: always
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: passbackendtrackerword
      MYSQL_DATABASE: demo_tracker_mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 20
    ports:
      - "3306:3306"
